version: "3.9"

services:
  client:
    container_name: client
    build: ./client
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - "3000:3000"

  server:
    container_name: server
    build: ./server
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - "8080:8080"

  database:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "adjunct-results-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "16psjvYpp"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./server/migrations/init:/docker-entrypoint-initdb.d
    ports:
      - "5432"

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx.conf
    links:
      - client
